# Generated by Django 5.1.7 on 2025-06-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productiamge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
